### ISSUE TITLE
Escribir el guion nivel 1

### ISSUE THREAD

**Issue by vcalzadaga** [CIFP-Jose-luis-Garci/ReturnToEarth#1]

**Comment by bonie3d** [comment]
[Guión.pdf](https://github.com/CIFP-Jose-luis-Garci/ReturnToEarth/files/7470245/Guion.pdf)

**Comment by bonie3d** [comment]
[Guión2.pdf](https://github.com/CIFP-Jose-luis-Garci/ReturnToEarth/files/7493014/Guion2.pdf)

Guión por verificar.

**Comment by vcalzadaga** [comment]
Hasta que no esté completo, no marquéis "Close". Debéis cerrarlo y pasarlo a "Verify" cuando esté completo del todo

**Comment by bonie3d** [comment]
[RevisionCarlos_Capitulo1.pdf](https://github.com/CIFP-Jose-luis-Garci/ReturnToEarth/files/7504163/RevisionCarlos_Capitulo1.pdf)

**Comment by vcalzadaga** [comment]
Lo dicho, añadid los cambios ortográficos que os comenté y ya estaría. Una cosa menos

**Comment by bonie3d** [comment]
[Guión_Final.pdf](https://github.com/CIFP-Jose-luis-Garci/ReturnToEarth/files/7515261/Guion_Final.pdf)
