### ISSUE TITLE
Dinámicas y Mecánicas

### ISSUE THREAD

**Issue by JVR4DO** [CIFP-Jose-luis-Garci/ReturnToEarth#12]

**Comment by JVR4DO** [comment]
o Controles: 
Puedes jugar a Return To Earth con teclado y ratón pero también puedes usar un gamepad.
![image](https://user-images.githubusercontent.com/90464928/140804089-37881ebf-1030-4299-9f8d-6f5444dd7e1e.png)
![image](https://user-images.githubusercontent.com/90464928/140804100-3c2b4d2a-10ab-4dc2-a7d7-85840ccd0140.png)

o Interacción entre elementos 
Return to Earth se desarrolla sobre un plano y los personajes pueden desplazarse por él. El escenario presentará ciertos obstáculos como puzzles que deberán ser resueltos para avanzar. 
En definitiva, las interacciones que se producirán son : 
Personaje - Personaje
Personaje - Escenario
Personaje - Puzzle

- DISEÑO DE NIVELES

o Objetivo del jugador
Resolver todos los puzzles que el juego te plantea para avanzar en la historia y saber el gran final de Return To Earth.

o Flujo de juego: 
El recorrido que tendrá que llevar a cabo el jugador es lo primero de todo reconocer que es lo que le está pidiendo el juego que haga (puzzles, recoger objetos, hablar con alguien…), después de reconocer lo que tiene que hacer, lo tendrá que realizar para así completar la misión y avanzar en la historia para saber el final del juego que es la motivación principal.

o Niveles del juego: 
Los niveles de Return to Earth se basarán en la resolución de puzzles y rompecabezas donde tendrás que recoger objetos ,completar mapas, o descifrar puzzles de desplazamiento.
Para comenzar veremos una animación donde están todos reunidos y Clonk se tira un pedo y a partir de ahí se comienza el nivel. Hablando sobre el nivel que vamos a desarrollar es un nivel donde tendrás que resolver 1 puzzle por cada jugador en la nave. El primero de ellos es un puzzle de Clonk donde tendrá que mover cajas para habilitar a Chakal un camino para llegar a un conducto de ventilación que le llevará a su habitación. Ese conducto es el segundo puzzle en el que chakal tendrá que completar un laberinto para llegar a su habitación. El tercer puzzle será una recogida de partes de un mapa de la tierra y por último cuando Viktor se acerca a su habitación la nave se choca contra un asteroide y tiene que ir a hackear el panel de la nave para recalcular el rumbo después de recalcular la ruta habrá un minijuego final donde tendrás que controlar la nave y esquivar los asteroides y cuando llegues a cierta distancia la nave se estrellará si o si con un asteroide y saltará una animación donde se ve la nave cayendo hacia la Tierra.

o Dificultad: 
![image](https://user-images.githubusercontent.com/90464928/140804275-dc930210-b79e-4ee1-b396-80aa0f375a3b.png)

o Tutorial: 
El tutorial es en sí el primer nivel ya que verás las mecánicas principales como el movimiento o la interacción de cada uno de los personajes con los diferentes elementos del nivel.

**Comment by vcalzadaga** [comment]
Aunque no desarrolléis el resto de niveles, indicad cuáles son así como algunas características generales de cada uno de ellos (complejidad, dificultad, tipo de puzzles a resolver, parte de la historia que tratan...)

**Comment by JVR4DO** [comment]
Ya lo he actualizado :)
