### ISSUE TITLE
Música y Efectos

### ISSUE THREAD

**Issue by bonie3d** [CIFP-Jose-luis-Garci/ReturnToEarth#13]
Información música y efectos de RTE.
Investigación y referencias visuales y musicales.

**Comment by bonie3d** [comment]
- MÚSICA Y EFECTOS:

Sonidos futuristas, canciones ambientadas en el espacio exterior, melodías cibernéticas.
El estilo sonoro de RTE va a ser muy variado, la banda sonora del juego tendrá muchas influencias musicales, desde música más clásica o ambiental a música más electrónica o experimental.
Durante el juego habrá música de fondo acorde al escenario, la música será ambiental y atmosférica.
Dependiendo de la situación en la que nos encontremos en el juego, la música irá siempre con una coherencia gráfica y visual, queremos que la música sea parte de las emociones de los jugadores.

La B.S.O. ha sido creada por nosotros, todas las canciones que incluimos son originales e inéditas. La composición ha sido personalizada y preparada para este juego.

Música Menú principal: música ambiental y experimental.
Juego: Música animada y que conecte con el jugador.
Pausa del juego: Música relajante.
Resolución Puzzles: música breve sonora al completar un desafio.
.


Música Menú Principal: Song X1.
Música Cinemática: Song X2.
Música Nivel 1: Song X3.
Música Lluvia de Asteródides: Song X4.


Efectos Sonoros dentro del Juego:

Sonido de apertura de puertas: Effects sounds
Alarmas Nave: Effects sounds
Asteroides: Effects sounds
Sonido Ambiental Nave: Effects sounds
Cajas Puzzles: Effects sounds
Rayos Eléctricos: Effects sounds
Sonido Chapa Ventilación: Effects sounds
Papeles: Effects sounds
Personajes: Effects sounds







Música inspiradora de otros videojuegos:

 
Dark Souls: Una banda sonora sobrecogedora e impactante.
https://www.youtube.com/watch?v=epK4CBE4bB8

 

Skyrim: Una mezcla sonora de ambientes, fantasía, silencios en el juego.
https://www.youtube.com/watch?v=aQeIYVM3YBM

  

Bioshock: Banda sonora llena de emociones y con mucha intensidad.
https://www.youtube.com/watch?v=JUAYFoRWU5g

- REFERENTES:
Como referencia del tratamiento de la cámara  ¾ top down, y estética pixel art, destacamos a la saga de “Pokemón” y la de “ The leyend of Zelda”.

 


En lo que se refiere a gama de color y esquemas de iluminación tomamos como referencia el videojuego “Hades” de Supergiant Games de 2020, así como la película de Ridley Scott de 1979 “Alien: El octavo pasajero”.

 

Sobre el tratamiento narrativo-visual (desvelar y descubrir) “Opossum Country” del desarrollador Ben Jelter en 2020 y “Noita” de Nolla Games en 2020, han sido referencias clave.

 




Videojuegos Pixel Art de referencia:

  

Octopath Traveler: Nivel gráfico de alta calidad y sistema de combate.
  
OwlBoy: Niveles de plataformas en 2d impresionantes y la diversión del juego.
  
Children of Morta: El tipo de animaciones y el diseño de los escenarios.

Star Renegades: Buena jugabilidad y estilo pixel art muy detallado.

Películas de referencia:

  

Alien: La intriga y el misterio de la historia.
Blade Runner: Aspectos visuales y escenarios.
Guardians of the Galaxy: La música, fotografía y aspectos narrativos en forma de comedia.
Star Wars: La historia y el peso de sus personajes dentro de ella.

**Comment by vcalzadaga** [comment]
kjker
![descarga](https://user-images.githubusercontent.com/74154291/140806201-3ec3afe7-8a67-4f1e-8a9c-1884176cab7f.jpg)
j
