### ISSUE TITLE
Estilo Visual - Diseño de escenarios

### ISSUE THREAD

**Issue by AlejandroLechon** [CIFP-Jose-luis-Garci/ReturnToEarth#17]

**Comment by AlejandroLechon** [comment]
Los escenarios de Return to Earth deben ser un personaje más en la historia. Son el vestigio de siglos de devastación y soledad. Un espejo del pasado. De esta manera no solo forman parte de la trama, sino que la completan y estructuran. 

![MAPA_NAVE](https://user-images.githubusercontent.com/90465448/140807273-21b14a2f-a4be-4801-9ef6-b6709b7e2df9.png)
![MAPA_CIUDAD](https://user-images.githubusercontent.com/90465448/140807286-8dfd3be6-1e95-4fda-9d98-760dde44c3d3.png)

**Comment by vcalzadaga** [comment]
Gran trabajo
