### ISSUE TITLE
- PÚBLICO OBJETIVO (TARGET):

### ISSUE THREAD

**Issue by cricosan** [CIFP-Jose-luis-Garci/ReturnToEarth#24]
# PÚBLICO OBJETIVO (TARGET): 
El público objetivo de Return to Earth es la generación Z, una generación que está ahora llegando a la mayoría de edad y que se caracteriza por el uso nativo de las tecnologías, la búsqueda de interacción con los ámbitos de su entorno y una gran implicación las causas sociales y medioambientales. Sólo la descripción de la generación nos hace darnos cuenta lo muy ligados que están los valores de nuestro videojuegos con los valores de la nueva juventud. 

Nuestro juego, que aboga por la importancia del medio ambiente y reflexiona sobre un futuro incierto, está dirigido a las personas a las que más va a afectar y por tanto, a las que más involucradas están en cambiarlo. 

Si nos detenemos a leer el informe de la Asociación Española de Videojuegos, podemos observar los siguientes datos: 
1) Que en la franja de edad de 15-24 años se concentran el 14% de los jugadores de videojuegos (el segundo tramo de edad más extenso después de 25-34). Nuestro videojuego, entendido para adolescentes mayores de 16 años, abarca una banda muy ancha de consumidores. Se mueve en un mercado grande.
2) El porcentaje de mujeres frente al de hombres en la industria, crece a cada año, siendo el 2020 un 3% más que el anterior y consolidándose en un generoso 47%. Return to Earth, libre de combates o escenas de lucha, es la opción ideal para un sector que prefiere los juegos orientados a la narrativa y la interactividad con los espacios.
3) El smartphone y el pc, suponen respectivamente, un 20% y 18% de los dispositivos más utilizados quedando así en 2º y 3º puesto frente a un consolidado 25% en consolas. El estilo pixel Art facilita la integración del juego a dispositivos móviles por su poco peso en gráficos. Además, y volviendo a recalcar que nuestro juego no tiene combate, es facilmente jugable sin mandos de consola pues con simples teclas o botones, una jugabilidad satisfactoria está más que garantizada.

En definitiva, Return to Earth se amolda perfectamente no solo a la generación a la que está dirigida, si no que también sigue los nuevos patrones de mercado consiguiendo maximizar la efectividad que tiene en su público objetivo.

**Comment by vcalzadaga** [comment]
Justo lo que buscaba. Muy bien
