### ISSUE TITLE
Equipo humano de RTE. Descripción de cada miembro.

### ISSUE THREAD

**Issue by AlejandroLechon** [CIFP-Jose-luis-Garci/ReturnToEarth#28]

**Comment by AlejandroLechon** [comment]
**Alejandro Lechón:** mis labores en Return to Earth están destinadas al diseño visual y desarrollo gráfico. De tal manera me encargo del diseño de arte como artista conceptual, y artista de pixel art. Elaboro sprites de personajes, escenarios, objetos,mapas, interfaces y aspecto visual de puzles conjunto con Celia Rico. También llevaré a cabo las funciones de técnico de Layout e iluminador cuando llegue el momento. Me considero un trabajador creativo y cooperativo. Me gusta escuchar a mis compañeros y debatir sobre dilemas técnicos que deben reflejarse estéticamente. Estoy motivado y preparado para hacer de Return to Earth un videojuego sólido, profesional y divergente.

**Comment by JVR4DO** [comment]
**Sergio Jurado:** En RTE yo soy el encargado de las mecánicas, dinámicas y la creación de todos los puzzles que aparecerán en él. Yo soy el encargado de crearlos y más tarde pasarle mis conceptos a los grandes artistas que tenemos en este grupo para que le den vida a mis puzzles. Además de eso me encargaré de la programación de RTE junto a alguno de mis compañeros.

![Foto](https://user-images.githubusercontent.com/90464928/141447910-d92c10b7-a583-487d-88f3-74aa07557c5e.png)

**Comment by Carlitos1301** [comment]
Carlos Torres: Mis labores en Return to Earth están enfocadas a la creación del guión, al diseño de los niveles y a la creación de las mecánicas. Aparte de todo esto ayudaré a mis compañeros con las demás labores siempre que lo necesiten ya que este proyecto somos todos y aunque tengamos tareas asignadas siempre hay que echar una mano en cualquier cosa. Soy una persona trabajadora, entusiasta y soñadora, tengo muchas ganas de terminar este proyecto ya que veo un gran potencial en él.

![WhatsApp Image 2021-05-25 at 17 22 53 (1)](https://user-images.githubusercontent.com/90465521/141450960-01314827-f528-4959-95f3-5b4ad0188051.jpeg)

**Comment by cricosan** [comment]
Celia Rico: Mi aportación en Return to Earth empezó con el desarrollo de concepto y narrativa de la idea semilla del juego. Plasmar ideas ya sea por escrito o en imagen, es lo que mejor se me da. Por eso, también he trabajado en el diseño de personajes, mapas y objetos. Mi intención final es que todo lo que pueda ser considerado comunicación de algún tipo, llegue de la forma más clara, más interesante y más estética al espectador. 

![image](https://user-images.githubusercontent.com/90465374/141454683-6b5fddcc-0a8b-4847-85e6-cae391324f0b.png)

**Comment by cricosan** [comment]
David R.Alcolea: Dentro del proyecto me he dedicado al Guión y la parte narrativa del juego. Carlos y yo hemos desarrollado la historia de los personajes y características del entorno de la historia en general. Con todo el equipo de trabajo al final del proyecto matizamos algunos aspectos y alguna idea nueva para concluir el trabajo.
He colaborado en la parte artística con bocetos e ideas sobre personajes, mapas, objetos, etc. Me he encargado de la parte sonora del juego, las canciones son originales y exclusivas para RTE. Todos los sonidos, temas y efectos han sido elaborados por nosotros.
