### ISSUE TITLE
Definir recorrido jugador

### ISSUE THREAD

**Issue by cricosan** [CIFP-Jose-luis-Garci/ReturnToEarth#7]

**Comment by vcalzadaga** [comment]
No hay ningún documento asociado a esta tarea por lo que asumo que falta. Lo vuelvo a pasar a In progress

**Comment by Carlitos1301** [comment]
Return to Earth comienza con un primer plano en el que observamos la sala de mandos de la nave en la que nuestros cuatro personajes están dialogando (breve presentación de estos, su nombre, y algunas frases en las que el jugador puede tener una primera idea de cómo será la personalidad de estos)
Tras finalizar el diálogo, ocurre algo (pedo clonk) que haces que los personajes se levanten y se vayan a sus respectivas habitaciones, uno por uno enseñaran al jugador sus diferentes habilidades resolviendo los puzzles.
El jugador empezará jugando con Clonk, para ello el jugador deberá llevar el personaje hasta la habitación de chakal donde tendrán una breve conversación (la caja que está en medio) y el jugador deberá de hacer el puzzle.
Una vez terminado el jugador controlará a chakal, tras abrirse el conducto que taponaba la caja chakal podrá pasar y deberá llegar hasta su habitación por los conductos (habitación chakal cerrada) para ello deberá de.utilizar su olfato guiándose a través del siguiente juego (laberinto)
El tercer personaje será Nemea, el jugador aparecerá en su habitación y la controlará, tras un breve diálogo dónde está explica que debe de encontrar.un mapa que ha perdido por la.nave, aquí comenzará el siguiente puzzle donde el jugador manejara a Nemea por la nave usando la intuitiva de esta para buscar el mapa.
Por último la nave temblará por el impacto del meteorito, todos los personajes se reunirán y tras un diálogo entre los personajes el jugador controlará a Víctor para resolver el último puzzle del juego, un rompecabezas eléctrico para arreglar la naves y aterrizar sanos y salvos
![Captura](https://user-images.githubusercontent.com/90465521/140975613-4135a272-6582-43ef-a0a7-d05a218cc9c5.PNG)
.

**Comment by vcalzadaga** [comment]
Añadid el recorrido desde que el jugador inicia el juego. Es decir, desde que se inicia el juego (navegación por los menús de inicio y de pausa incluidos)

Simplemente basta con añadir esta información, el resto está bien. Una vez incluido, podéis cerrar el issue de nuevo
