### ISSUE TITLE
Crear interfaz pixel art

### ISSUE THREAD

**Issue by cricosan** [CIFP-Jose-luis-Garci/ReturnToEarth#9]

**Comment by AlejandroLechon** [comment]
Ya tenemos la interfaz. Adjunto pruebas de color.
![Ui_test_chakal](https://user-images.githubusercontent.com/90465448/143769333-41e8e589-f720-4c5c-8c4f-b0b0fcd7071c.png)
![Ui_test_clonk](https://user-images.githubusercontent.com/90465448/143769335-116b2d51-bad5-47a9-b720-b3b7c88d732e.png)
![Ui_test_nemea](https://user-images.githubusercontent.com/90465448/143769336-071ad0c0-39cc-4acb-a52b-f294be1ddf44.png)
![Ui_test_viktor](https://user-images.githubusercontent.com/90465448/143769339-fe578298-657f-489d-bf1b-47a040797179.png)
